---
title: 在博客中添加互动图
author: 李泉
date: '2019-01-24'
slug: plotly
categories:
  - R
tags:
  - Blogdown
description: ''
topics: [R]
---

浏览网页时经常可以发现有些图可以提供动态信息，鼠标光标在图上移动，就可以显示出相应信息。在R中绘制这种图依靠的包是Plotly。

下面这张图就是利用plotly包里面的economics数据框，绘制的失业率，在图中移动光标，就可以看到具体年份的数据。

```{r, message=F, warning=F}
library(plotly)
p<-plot_ly(economics, x=~date, y=~unemploy/pop)
p
```

如果想修改图的坐标轴名称和添加图的名称，可以做如下改动：

```{r, message=F, warning=F}
library(dplyr)
library(plotly)

p<-plot_ly(economics,x=~date, y=~unemploy/pop)

p %>%
layout(xaxis= list(title= "日期"), yaxis=list(title="失业率"), title ="美国失业率")

```

整合起来可以这么写：

```{r, message=F, warning=F}
library(plotly)
library(dplyr)
economics %>%
  plot_ly(x=~date, y=~unemploy/pop) %>%
  layout(xaxis= list(title= "日期"),yaxis=list(title="失业率"),title="美国失业率")
```



plotly和ggplot结合起来可以完成更复杂的工作。比如对安斯科姆数据集的处理(Anscombe’s quartet ):

数据的原始形态如下,四个数据集中分别含有x和y，记为x1,x2,x3,x4,y1,y2,y3,y4：


```{r,message=F,warning=F}
library(dplyr)
library(tidyr)
library(knitr)
head(anscombe)
anscombe%>% 
  knitr::kable("html", caption = '安斯科姆数据集')
```

整理转换之后变成：

```{r,message=F,warning=F}
library(dplyr)
library(tidyr)

anscombe_tidy <- anscombe %>%
    mutate(observation = seq_along(x1)) %>%
    gather(key, value, -observation) %>%
    separate(key, c("variable", "set"), 1, convert = TRUE) %>%
    mutate(set = as.character(as.roman(set))) %>%
    spread(variable, value) %>%
    arrange(set)
head(anscombe_tidy)

```


方便更好的认识数据，可以用DT包：

```{r,message=F,warning=F}
library(dplyr)
library(tidyr)
library(DT)
anscombe_tidy %>% 
datatable(rownames = FALSE, 
          options = list(
            pageLength = 11, 
            autoWidth = TRUE, 
            columnDefs = list(list(
              className = 'dt-left', 
              targets = 0),
              list(className = 'dt-center', targets = 1))))

```


再利用plotly和ggplot作图：

```{r,message=F,warning=F}

library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
cols <- c("#0072B2", "#009E73", "#D55E00", "#CC79A7")
ans_plot <- ggplot(anscombe_tidy, aes(x, y, colour = set)) +
  geom_point(size = 3, alpha = .7) +
  geom_smooth(method = "lm", se = FALSE) + 
  facet_wrap(~ set) +
  theme_bw() +
  theme(legend.position="none") +
  scale_colour_manual(values = cols) 

ggplotly(ans_plot)

```

[原始说明链接](https://blogdown-demo.rbind.io/2017/09/07/adding-htmlwidgets-to-r-markdown-posts/)